/**
 * BULK DATA INGESTION FRAMEWORK
 * 
 * Handles all data sources that are file-based rather than live APIs.
 * 
 * Sources managed here:
 *   MIT Election Lab    → Historical election results (partisan lean)
 *   Pew Research        → Issue polling datasets (quarterly update)
 *   OpenSecrets         → Campaign finance bulk data (when approved)
 *   GovTrack            → Congressional voting records (replaces ProPublica)
 *   ANES                → American National Election Studies
 *   GSS                 → General Social Survey
 *   ProPublica Archive  → House Office Expenditures (how incumbents spend)
 * 
 * How it works:
 *   1. Files are uploaded to /data/raw/ (or auto-downloaded from GitHub)
 *   2. Each source has a parser that normalizes to our schema
 *   3. Normalized data upserts into PostgreSQL
 *   4. Redis cache invalidated for affected districts
 *   5. Feature flag DATASET_[NAME]_LOADED set to 'true' when complete
 * 
 * Run via: node src/jobs/ingest.js --source=mit-election-lab
 * Or via Bull queue: jobs/ingestion-queue.js
 */

const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');

// Raw data directory — put downloaded files here
const RAW_DATA_DIR = path.join(process.cwd(), 'data', 'raw');
const PROCESSED_DIR = path.join(process.cwd(), 'data', 'processed');

// ─────────────────────────────────────────────────
// SOURCE REGISTRY
// ─────────────────────────────────────────────────

const BULK_SOURCES = {

  'mit-election-lab': {
    name: 'MIT Election Data + Science Lab',
    description: 'Historical election results: House (1976-2024), Senate (1976-2024), President (1976-2024), precinct-level (2016-2024)',
    status: process.env.DATASET_MIT_ELECTION_LAB_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      1. Go to: https://electionlab.mit.edu/data
      2. Download these datasets (Harvard Dataverse):
         - 1976-2024-house.csv (House returns)
         - 1976-2024-senate.csv (Senate returns)
         - 1976-2024-president.csv (Presidential returns)
      3. Also from GitHub: https://github.com/MEDSL
         - 2024-elections-official (most recent precinct data)
      4. Place all files in: data/raw/mit-election-lab/
      5. Run: node src/jobs/ingest.js --source=mit-election-lab
    `,
    targetTable: 'historical_election_results',
    parser: parseMitElectionLab,
    envFlag: 'DATASET_MIT_ELECTION_LAB_LOADED',
  },

  'pew-research': {
    name: 'Pew Research Center Datasets',
    description: 'Issue polling on politics, policy, social trends. Key source for district-level issue polling history.',
    status: process.env.DATASET_PEW_RESEARCH_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      Download from: https://www.pewresearch.org/datasets/
      Filter by: Politics & Policy, Economy
      Download individual ATP wave SPSS files (.sav)
      Place files in: data/raw/pew-research/
    `,
    targetTable: 'pew_survey_responses',
    parser: parsePewResearch,
    envFlag: 'DATASET_PEW_RESEARCH_LOADED',
  },

  'pew-waves': {
    name: 'Pew Research — Individual ATP Waves',
    description: 'Upload individual American Trends Panel wave files as they are released. Add new waves anytime without re-running the full dataset.',
    status: process.env.DATASET_PEW_WAVES_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      Download individual ATP wave zip files from: https://www.pewresearch.org/datasets/
      Extract the .sav file from each zip and upload here.
      New waves can be added at any time — the ingestion is additive.
      Currently have: W141-W163 (Jan 2024 - Feb 2025)
    `,
    targetTable: 'pew_survey_responses',
    parser: parsePewResearch,
    envFlag: 'DATASET_PEW_WAVES_LOADED',
  },

  'election-intelligence': {
    name: 'Processed Election Intelligence',
    description: 'Upload district_partisan_lean.csv, district_intelligence.csv, competitive_districts.csv — processed from MIT Election Lab data. Powers the candidate district intelligence dashboard.',
    status: process.env.DATASET_ELECTION_INTELLIGENCE_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      These files were generated by the Party of You election data processor
      from MIT Election Lab public data. They are ready to load directly.
      
      Files to upload:
        - district_partisan_lean.csv    (599 districts, lean index + label)
        - district_intelligence.csv     (full district profiles with trend)
        - competitive_districts.csv     (276 districts within 12 points)
        - state_summary.csv             (state-level district breakdown)
    `,
    targetTable: 'district_partisan_lean',
    parser: parseElectionIntelligence,
    envFlag: 'DATASET_ELECTION_INTELLIGENCE_LOADED',
  },

  'election-history': {
    name: 'Election History — MIT Constituency Returns',
    description: 'Raw MIT Election Lab CSV files: 1976-2018-house.csv, 1976-2018-senate.csv, 1976-2016-president.csv, plus 2024 state-level files for Senate and President. Upload all files together — the parser handles each automatically.',
    status: process.env.DATASET_ELECTION_HISTORY_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      Upload these files together:
        - 1976-2018-house.csv
        - 1976-2018-senate.csv
        - 1976-2016-president.csv
        - 2024-senate-state.csv
        - 2024-president-state.csv
        - 2024-senate-county.csv (if available)
        - 2024-president-county.csv (if available)
      Parser normalizes column names automatically across all file formats.
    `,
    targetTable: 'historical_election_results',
    parser: parseElectionHistory,
    envFlag: 'DATASET_ELECTION_HISTORY_LOADED',
  },

  'precinct-2024': {
    name: '2024 Precinct Data by Congressional District',
    description: '2024 actual results aggregated to congressional district level. 4,166 districts across 47 states.',
    status: process.env.DATASET_PRECINCT_2024_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      File to upload: precinct_district_2024.csv
      Generated from MIT Election Lab 2024 precinct-level state files.
    `,
    targetTable: 'precinct_results_2024',
    parser: parsePrecinct2024,
    envFlag: 'DATASET_PRECINCT_2024_LOADED',
  },


  'opensecrets': {
    name: 'OpenSecrets Bulk Data',
    description: 'Campaign finance industry categorization. Requires approved bulk data access — currently unavailable. FEC API covers raw contribution data directly.',
    status: 'unavailable',
    downloadInstructions: `
      OpenSecrets discontinued their API in April 2025.
      Bulk data requires an approved account and educational use agreement.
      We are covering this use case directly via the FEC API instead.
      The FEC API provides raw contribution data; we build our own
      industry categorization from publicly available employer/occupation fields.
    `,
    targetTable: 'campaign_finance_enriched',
    parser: parseOpenSecrets,
    envFlag: 'DATASET_OPENSECRETS_LOADED',
    hidden: true,  // Don't show in admin dashboard
  },

  'govtrack': {
    name: 'GovTrack Congressional Voting Records',
    description: 'Every congressional vote, bill, and member profile since 1789. Replaces ProPublica Congress API.',
    status: process.env.DATASET_GOVTRACK_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      GovTrack publishes data publicly on GitHub — no account needed.
      
      1. Bulk vote data: https://www.govtrack.us/data/congress/
         Or GitHub mirror: https://github.com/unitedstates/congress
         
      2. PRIORITY downloads:
         - votes/ directory for current + last 2 congresses (118, 117, 116)
         - legislators-current.csv (active members with party, district)
         - legislators-historical.csv (all historical members)
         
      3. For votes, download the JSON roll call files:
         congress/{congress}/votes/{session}/{vote-type}{number}/data.json
         
      4. Place in: data/raw/govtrack/
      5. Run: node src/jobs/ingest.js --source=govtrack
      
      KEY USE CASE: "Your incumbent voted [X] on these issues affecting you"
      We show candidates a pre-built incumbent voting record profile.
    `,
    targetTable: 'voting_records',
    parser: parseGovTrack,
    envFlag: 'DATASET_GOVTRACK_LOADED',
  },

  'propublica-expenditures': {
    name: 'ProPublica House Office Expenditures',
    description: 'How each House member spends their official office budget. Useful for "your rep spent $X on [thing] while voting against Y".',
    status: process.env.DATASET_PROPUBLICA_EXPENDITURES_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      1. Go to: https://projects.propublica.org/datastore/#house-office-expenditures
      2. Download: house-office-expenditures-with-readme.zip (74MB)
      3. Extract and place CSV files in: data/raw/propublica-expenditures/
      4. Run: node src/jobs/ingest.js --source=propublica-expenditures
      
      COVERAGE: July 2009 - March 2018 (not updated — historical only)
      USE: Background research on long-serving incumbents
    `,
    targetTable: 'house_expenditures',
    parser: parseProPublicaExpenditures,
    envFlag: 'DATASET_PROPUBLICA_EXPENDITURES_LOADED',
  },

  'gss': {
    name: 'General Social Survey (GSS)',
    description: 'Political views, party ID, economic attitudes, confidence in institutions. 2021, 2022, 2024 cross-sectional studies.',
    status: process.env.DATASET_GSS_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      Files you downloaded from gss.norc.org:
        GSS 2024 cross-sectional (.sav)
        GSS 2022 cross-sectional (.sav)
        GSS 2021 cross-sectional (.sav)
      Place all .sav files in: data/raw/gss/
      Run: node src/jobs/ingest.js --source=gss
    `,
    targetTable: 'gss_survey_responses',
    parser: parseGSS,
    envFlag: 'DATASET_GSS_LOADED',
  },

  'anes': {
    name: 'American National Election Studies',
    description: 'Gold standard voter behavior research. Cumulative file 1948-2020 plus 2020, 2016, 2012 time series.',
    status: process.env.DATASET_ANES_LOADED === 'true' ? 'loaded' : 'pending',
    downloadInstructions: `
      Download from electionstudies.org (requires free account):
        - ANES 2020 Time Series Study (SPSS .sav)
        - ANES 2016 Time Series Study (SPSS .sav)
        - ANES Cumulative Data File 1948-2020 (SPSS .sav or tab-delimited)
      Place all files in: data/raw/anes/
      Run: node src/jobs/ingest.js --source=anes
    `,
    targetTable: 'anes_survey_responses',
    parser: parseANES,
    envFlag: 'DATASET_ANES_LOADED',
  },

};

// ─────────────────────────────────────────────────
// INGESTION RUNNER
// ─────────────────────────────────────────────────

/**
 * Main ingestion function — call with source name
 * node src/jobs/ingest.js --source=mit-election-lab
 */
async function ingestSource(sourceName, db, options = {}) {
  const source = BULK_SOURCES[sourceName];
  if (!source) {
    throw new Error(`Unknown source: ${sourceName}. Available: ${Object.keys(BULK_SOURCES).join(', ')}`);
  }

  console.log(`\n═══════════════════════════════════════`);
  console.log(`Ingesting: ${source.name}`);
  console.log(`Target table: ${source.targetTable}`);
  console.log(`═══════════════════════════════════════\n`);

  const rawDir = path.join(RAW_DATA_DIR, sourceName);

  if (!fs.existsSync(rawDir)) {
    console.error(`Raw data directory not found: ${rawDir}`);
    console.log('\nDownload instructions:');
    console.log(source.downloadInstructions);
    return { success: false, reason: 'Raw data not found' };
  }

  const files = fs.readdirSync(rawDir).filter(f => f.endsWith('.csv') || f.endsWith('.json') || f.endsWith('.txt'));

  if (!files.length) {
    console.error(`No data files found in ${rawDir}`);
    console.log('\nDownload instructions:');
    console.log(source.downloadInstructions);
    return { success: false, reason: 'No files to process' };
  }

  console.log(`Found ${files.length} file(s): ${files.join(', ')}`);

  let totalRows = 0;
  let totalInserted = 0;
  let totalErrors = 0;

  for (const file of files) {
    const filePath = path.join(rawDir, file);
    console.log(`\nProcessing: ${file}`);

    try {
      const { rows, inserted, errors } = await source.parser(filePath, db, options);
      totalRows += rows;
      totalInserted += inserted;
      totalErrors += errors;
      console.log(`  ✓ ${rows} rows parsed, ${inserted} inserted/updated, ${errors} errors`);
    } catch (e) {
      console.error(`  ✗ Failed: ${e.message}`);
      totalErrors++;
    }
  }

  console.log(`\n═══════════════════════════════════════`);
  console.log(`Complete: ${totalInserted} records loaded from ${source.name}`);
  console.log(`Errors: ${totalErrors}`);
  console.log(`═══════════════════════════════════════\n`);

  if (totalInserted > 0) {
    console.log(`Set Railway env var: ${source.envFlag}=true`);
  }

  return { success: totalErrors === 0, totalRows, totalInserted, totalErrors };
}

// ─────────────────────────────────────────────────
// PARSERS — One per source
// ─────────────────────────────────────────────────

/**
 * MIT Election Lab parser
 * Handles House, Senate, and Presidential CSVs
 * Schema: state, district, year, office, candidate, party, votes, totalVotes
 */
async function parseMitElectionLab(filePath, db) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });

  let inserted = 0;
  let errors = 0;

  for (const row of rows) {
    try {
      // MIT MEDSL column names vary by file — handle both formats
      const state = row.state_po || row.state;
      const year = parseInt(row.year);
      const office = row.office || detectOfficeFromFilename(filePath);
      const district = row.district || null;
      const candidate = row.candidate;
      const party = normalizeParty(row.party_simplified || row.party);
      const votes = parseInt(row.candidatevotes || row.votes || 0);
      const totalVotes = parseInt(row.totalvotes || row.total_votes || 0);

      if (!state || !year || !candidate) continue;

      await db.query(`
        INSERT INTO historical_election_results 
          (state, district, year, office, candidate_name, party, votes, total_votes, source)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'MIT Election Lab')
        ON CONFLICT (state, district, year, office, candidate_name)
        DO UPDATE SET votes = EXCLUDED.votes, total_votes = EXCLUDED.total_votes
      `, [state, district, year, office, candidate, party, votes, totalVotes]);

      inserted++;
    } catch (e) {
      errors++;
      if (errors < 10) console.warn(`  Row error: ${e.message}`);
    }
  }

  return { rows: rows.length, inserted, errors };
}

/**
 * SPSS (.sav) file reader
 * Returns array of row objects. Field names normalized to uppercase.
 * Used by Pew Research, GSS, and ANES parsers.
 */
async function readSpssFile(filePath) {
  return new Promise((resolve, reject) => {
    const rows = [];
    let headers = null;
    let settled = false;

    // Timeout for very large files (5 minutes)
    const timeout = setTimeout(() => {
      if (!settled) {
        settled = true;
        console.warn(`[SPSS] Timeout reading ${path.basename(filePath)} after 5 min — returning ${rows.length} rows collected so far`);
        resolve(rows);
      }
    }, 5 * 60 * 1000);

    try {
      const SavReader = require('sav-reader');
      const reader = new SavReader(filePath);

      reader.on('header', (header) => {
        headers = header.fields.map(f => f.name.toUpperCase());
      });

      reader.on('data', (row) => {
        if (!headers) return;
        const obj = {};
        headers.forEach((h, i) => { obj[h] = row[i]; });
        rows.push(obj);
      });

      reader.on('end', () => {
        if (!settled) {
          settled = true;
          clearTimeout(timeout);
          resolve(rows);
        }
      });

      reader.on('error', (err) => {
        if (!settled) {
          settled = true;
          clearTimeout(timeout);
          // Return whatever we got rather than failing completely
          if (rows.length > 0) {
            console.warn(`[SPSS] Error after ${rows.length} rows: ${err.message} — returning partial data`);
            resolve(rows);
          } else {
            reject(err);
          }
        }
      });

      reader.read();
    } catch (err) {
      if (!settled) {
        settled = true;
        clearTimeout(timeout);
        reject(err);
      }
    }
  });
}

/**
 * Pew Research parser
 * Handles SPSS (.sav) files from American Trends Panel downloads.
 * Key variables extracted: party ID, issue priorities, approval ratings,
 * political ideology, economic sentiment.
 *
 * Pew ATP variable naming conventions:
 *   F_PARTY_FINAL  — party identification (1=Rep, 2=Dem, 3=Ind, 9=Other)
 *   F_PARTYLN_FINAL — lean direction for independents
 *   F_IDEO         — political ideology (1=Very conservative → 5=Very liberal)
 *   WEIGHT_W[N]    — survey weight for wave N
 *   INTERVIEW_START_W[N] or ENDDATE — survey date
 */
async function parsePewResearch(filePath, db) {
  const ext = path.extname(filePath).toLowerCase();
  const filename = path.basename(filePath);

  let rows;
  if (ext === '.sav') {
    console.log(`  Reading SPSS file: ${filename}`);
    rows = await readSpssFile(filePath);
  } else if (ext === '.csv') {
    const content = fs.readFileSync(filePath, 'utf-8');
    rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });
    // Normalize headers to uppercase
    rows = rows.map(r => {
      const norm = {};
      Object.entries(r).forEach(([k, v]) => { norm[k.toUpperCase()] = v; });
      return norm;
    });
  } else {
    console.log(`  Skipping unsupported file format: ${ext}`);
    return { rows: 0, inserted: 0, errors: 0 };
  }

  let inserted = 0;
  let errors = 0;

  // Detect wave number from filename (e.g., "ATP W120.sav" → wave 120)
  const waveMatch = filename.match(/W(\d+)/i);
  const waveNum = waveMatch ? parseInt(waveMatch[1]) : null;

  // Find weight variable — Pew uses WEIGHT_W[N] or WEIGHT
  const weightKey = rows[0]
    ? Object.keys(rows[0]).find(k => k.startsWith('WEIGHT')) || 'WEIGHT'
    : 'WEIGHT';

  for (const row of rows) {
    try {
      // Party identification — try multiple variable name patterns
      const party = row['F_PARTY_FINAL'] || row['PARTY'] || null;
      const partyLean = row['F_PARTYLN_FINAL'] || null;
      const ideology = row['F_IDEO'] || null;
      const weight = parseFloat(row[weightKey] || row['WEIGHT'] || 1);

      // Respondent ID — try multiple patterns
      const respId = row['RESPID'] || row['QKEY'] || row['CASEID'] || `pew-w${waveNum}-${inserted}`;

      // Survey date
      const surveyDate = row['INTERVIEW_START'] || row['ENDDATE'] ||
                         row[`INTERVIEW_START_W${waveNum}`] || null;

      // Extract key political variables as structured data
      const politicalData = {};

      // Issue priority variables (Pew often uses scale 1-4 or 1-5)
      const issueVars = ['ECON', 'HEALTH', 'CLIMATE', 'IMMIG', 'GUNS', 'EDUC',
                         'JOBS', 'INFRA', 'TAXES', 'HOUSING', 'WAGE'];
      issueVars.forEach(v => {
        if (row[v] !== undefined) politicalData[v.toLowerCase()] = row[v];
      });

      // Presidential/congressional approval
      ['PRESAPP', 'CONGAPP', 'JOBPRES', 'JOBCONG'].forEach(v => {
        if (row[v] !== undefined) politicalData[v.toLowerCase()] = row[v];
      });

      // Economic sentiment
      ['ECONEVAL', 'ECONDIRE', 'FINAN'].forEach(v => {
        if (row[v] !== undefined) politicalData[v.toLowerCase()] = row[v];
      });

      await db.query(`
        INSERT INTO pew_survey_responses
          (respondent_id, party, party_lean, ideology, weight,
           survey_date, wave_number, political_data, source_file)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (respondent_id, source_file) DO NOTHING
      `, [
        respId,
        party !== null ? String(party) : null,
        partyLean !== null ? String(partyLean) : null,
        ideology !== null ? String(ideology) : null,
        weight,
        surveyDate || null,
        waveNum,
        JSON.stringify(politicalData),
        filename,
      ]);

      inserted++;
    } catch (e) {
      errors++;
      if (errors <= 3) console.warn(`  Row error: ${e.message}`);
    }
  }

  return { rows: rows.length, inserted, errors };
}


/**
 * OpenSecrets parser
 * Multiple file types: CandX.txt, IndivX.txt, PACsX.txt
 * Pipe-delimited format
 */
async function parseOpenSecrets(filePath, db) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const filename = path.basename(filePath).toLowerCase();

  let rows, inserted = 0, errors = 0;

  if (filename.startsWith('cand')) {
    // Candidate summary file
    rows = parse(content, {
      columns: ['cycle', 'fecid', 'cid', 'name', 'party', 'state', 'seat', 'seatStatus',
                'seatResult', 'currCand', 'cycleCand', 'crpPri', 'pviState', 'indivs',
                'pacs', 'other', 'cands', 'total', 'spent', 'cash', 'debt'],
      delimiter: '|',
      skip_empty_lines: true,
      from_line: 2,
    });

    for (const row of rows) {
      try {
        await db.query(`
          INSERT INTO opensecrets_candidates
            (cycle, fec_id, crp_id, name, party, state, seat, total_raised, total_spent, cash_on_hand, debt)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
          ON CONFLICT (cycle, fec_id) DO UPDATE
          SET total_raised = EXCLUDED.total_raised, total_spent = EXCLUDED.total_spent
        `, [row.cycle, row.fecid, row.cid, row.name, row.party, row.state, row.seat,
            parseFloat(row.total || 0), parseFloat(row.spent || 0),
            parseFloat(row.cash || 0), parseFloat(row.debt || 0)]);
        inserted++;
      } catch (e) {
        errors++;
      }
    }
  } else if (filename === 'crp_categories.txt') {
    // Industry categorization file — most valuable single file
    rows = parse(content, {
      columns: ['catcode', 'catname', 'catorder', 'industry', 'sector', 'sectorlong'],
      delimiter: '|',
      skip_empty_lines: true,
      from_line: 2,
    });

    for (const row of rows) {
      try {
        await db.query(`
          INSERT INTO opensecrets_categories
            (cat_code, cat_name, industry, sector, sector_long)
          VALUES ($1, $2, $3, $4, $5)
          ON CONFLICT (cat_code) DO UPDATE
          SET cat_name = EXCLUDED.cat_name, industry = EXCLUDED.industry
        `, [row.catcode, row.catname, row.industry, row.sector, row.sectorlong]);
        inserted++;
      } catch (e) {
        errors++;
      }
    }
  }

  return { rows: rows?.length || 0, inserted, errors };
}

/**
 * GovTrack parser
 * JSON format from the congress data repository
 */
async function parseGovTrack(filePath, db) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const filename = path.basename(filePath);

  let inserted = 0;
  let errors = 0;

  if (filename === 'legislators-current.csv' || filename === 'legislators-historical.csv') {
    const rows = parse(content, { columns: true, skip_empty_lines: true });
    for (const row of rows) {
      try {
        await db.query(`
          INSERT INTO legislators
            (bioguide_id, full_name, party, state, district, chamber, start_date, end_date, govtrack_id)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
          ON CONFLICT (bioguide_id) DO UPDATE
          SET party = EXCLUDED.party, district = EXCLUDED.district
        `, [
          row.bioguide_id,
          `${row.first_name} ${row.last_name}`,
          row.party,
          row.state,
          row.district || null,
          row.type === 'sen' ? 'senate' : 'house',
          row.start_date || null,
          row.end_date || null,
          row.govtrack_id || null,
        ]);
        inserted++;
      } catch (e) {
        errors++;
      }
    }
    return { rows: inserted + errors, inserted, errors };
  }

  if (filename === 'data.json') {
    // Roll call vote file
    const vote = JSON.parse(content);
    try {
      await db.query(`
        INSERT INTO voting_records
          (vote_id, congress, session, chamber, vote_type, date, question, result, vote_counts, govtrack_source)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        ON CONFLICT (vote_id) DO NOTHING
      `, [
        vote.vote_id,
        vote.congress,
        vote.session,
        vote.chamber,
        vote.category,
        vote.date,
        vote.question,
        vote.result,
        JSON.stringify(vote.votes),
        filePath,
      ]);
      inserted++;
    } catch (e) {
      errors++;
    }
    return { rows: 1, inserted, errors };
  }

  return { rows: 0, inserted: 0, errors: 0 };
}

/**
 * ProPublica House Expenditures parser
 */
async function parseProPublicaExpenditures(filePath, db) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });

  let inserted = 0;
  let errors = 0;

  for (const row of rows) {
    try {
      // Summary file format
      if (row.CATEGORY && row.OFFICE) {
        await db.query(`
          INSERT INTO house_expenditures
            (bioguide_id, office_name, year, quarter, category, amount)
          VALUES ($1, $2, $3, $4, $5, $6)
          ON CONFLICT DO NOTHING
        `, [
          row.BIOGUIDE_ID || null,
          row.OFFICE,
          parseInt(row.YEAR),
          parseInt(row.QUARTER),
          row.CATEGORY,
          parseFloat(row.AMOUNT || row.YTD || 0),
        ]);
        inserted++;
      }
    } catch (e) {
      errors++;
    }
  }

  return { rows: rows.length, inserted, errors };
}

/**
 * GSS parser (General Social Survey)
 * Handles SPSS .sav files from gss.norc.org
 * Key variables: party ID, political views, economic attitudes, confidence in institutions
 *
 * GSS core variables we extract:
 *   PARTYID  — party identification (0=Strong Dem → 6=Strong Rep, 7=Other)
 *   POLVIEWS — political views (1=Extremely liberal → 7=Extremely conservative)
 *   YEAR     — survey year
 *   CONFED   — confidence in federal government
 *   CLASS_   — subjective class identification
 *   SATFIN   — satisfaction with financial situation
 *   EQWLTH   — should government reduce income differences (1=Strongly agree → 7=Strongly disagree)
 *   UNION_   — union membership
 *   WRKSTAT  — employment status
 */
async function parseGSS(filePath, db) {
  const ext = path.extname(filePath).toLowerCase();
  let rows;

  if (ext === '.sav') {
    rows = await readSpssFile(filePath);
  } else if (ext === '.csv') {
    const content = fs.readFileSync(filePath, 'utf-8');
    rows = parse(content, { columns: true, skip_empty_lines: true });
    rows = rows.map(r => {
      const norm = {};
      Object.entries(r).forEach(([k, v]) => { norm[k.toUpperCase()] = v; });
      return norm;
    });
  } else {
    return { rows: 0, inserted: 0, errors: 0 };
  }

  let inserted = 0;
  let errors = 0;

  for (const row of rows) {
    try {
      const year = parseInt(row['YEAR']) || null;
      if (!year) continue;

      const politicalData = {};
      const gssVars = ['PARTYID', 'POLVIEWS', 'CONFED', 'CONLEGIS', 'TRUST',
                       'CLASS_', 'SATFIN', 'EQWLTH', 'UNION_', 'WRKSTAT',
                       'RINCOM16', 'EDUC', 'RACE', 'SEX', 'AGE', 'REGION'];
      gssVars.forEach(v => {
        if (row[v] !== undefined && row[v] !== null) {
          politicalData[v.toLowerCase().replace('_', '')] = row[v];
        }
      });

      const id = row['ID_'] || row['ID'] || row['CASEID'] || `gss-${year}-${inserted}`;

      await db.query(`
        INSERT INTO gss_survey_responses
          (respondent_id, year, party_id, political_views, political_data, source_file)
        VALUES ($1, $2, $3, $4, $5, $6)
        ON CONFLICT (respondent_id, source_file) DO NOTHING
      `, [
        String(id),
        year,
        row['PARTYID'] !== undefined ? parseInt(row['PARTYID']) : null,
        row['POLVIEWS'] !== undefined ? parseInt(row['POLVIEWS']) : null,
        JSON.stringify(politicalData),
        path.basename(filePath),
      ]);

      inserted++;
    } catch (e) {
      errors++;
      if (errors <= 3) console.warn(`  GSS row error: ${e.message}`);
    }
  }

  return { rows: rows.length, inserted, errors };
}

async function parseANES(filePath, db) {
  const ext = path.extname(filePath).toLowerCase();
  let rows;

  if (ext === '.sav') {
    console.log(`  Reading ANES SPSS file...`);
    rows = await readSpssFile(filePath);
  } else if (ext === '.csv' || ext === '.tsv') {
    const content = fs.readFileSync(filePath, 'utf-8');
    rows = parse(content, {
      columns: true,
      skip_empty_lines: true,
      delimiter: ext === '.tsv' ? '\t' : ',',
    });
    rows = rows.map(r => {
      const norm = {};
      Object.entries(r).forEach(([k, v]) => { norm[k.toUpperCase()] = v; });
      return norm;
    });
  } else {
    console.log(`  Skipping unsupported ANES format: ${ext}`);
    return { rows: 0, inserted: 0, errors: 0 };
  }

  let inserted = 0;
  let errors = 0;

  // ANES key variables (vary slightly between cumulative and time series)
  // Cumulative file: VCF prefix. Time series: V prefix.
  for (const row of rows) {
    try {
      // Detect variable naming convention
      const isCumulative = Object.keys(row).some(k => k.startsWith('VCF'));
      const prefix = isCumulative ? 'VCF' : 'V';

      // Year
      const year = parseInt(row[`${prefix}0004`] || row['YEAR'] || row['VCF0004']) || null;
      if (!year) continue;

      // Party identification (7-point scale)
      const partyId = row[`${prefix}0301`] || row[`${prefix}9008`] || null;

      // Liberal-conservative self-placement (7-point)
      const ideology = row[`${prefix}0803`] || null;

      // Presidential approval / thermometer
      const presTherm = row[`${prefix}0424`] || row[`${prefix}9218`] || null;

      // Turnout / voted
      const voted = row[`${prefix}0702`] || row[`${prefix}9010`] || null;

      const politicalData = {};
      ['VCF0301','VCF0803','VCF0424','VCF0702','VCF0606','VCF0618',
       'VCF9008','VCF9010','VCF9218'].forEach(v => {
        if (row[v] !== undefined) politicalData[v.toLowerCase()] = row[v];
      });

      const id = row['VCF0006'] || row['VERSION'] || row['CASEID'] || `anes-${year}-${inserted}`;

      await db.query(`
        INSERT INTO anes_survey_responses
          (respondent_id, year, party_id, ideology, voted,
           political_data, source_file)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (respondent_id, source_file) DO NOTHING
      `, [
        String(id),
        year,
        partyId !== null ? String(partyId) : null,
        ideology !== null ? String(ideology) : null,
        voted !== null ? String(voted) : null,
        JSON.stringify(politicalData),
        path.basename(filePath),
      ]);

      inserted++;
    } catch (e) {
      errors++;
      if (errors <= 3) console.warn(`  ANES row error: ${e.message}`);
    }
  }

  return { rows: rows.length, inserted, errors };
}

// ─────────────────────────────────────────────────
// PROCESSED ELECTION INTELLIGENCE PARSERS
// These handle the pre-processed CSVs generated by
// the Party of You election data processor script.
// ─────────────────────────────────────────────────

/**
 * Parses district_partisan_lean.csv, district_intelligence.csv,
 * competitive_districts.csv, and state_summary.csv into the
 * district_partisan_lean and district_intelligence tables.
 */
async function parseElectionIntelligence(filePath, db) {
  const filename = path.basename(filePath).toLowerCase();
  const content = fs.readFileSync(filePath, 'utf-8');
  const rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });

  let inserted = 0;
  let errors = 0;

  // Ensure tables exist
  await db.query(`
    CREATE TABLE IF NOT EXISTS district_partisan_lean (
      id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      state           CHAR(2) NOT NULL,
      office          TEXT NOT NULL,
      district        TEXT NOT NULL,
      lean_index      DECIMAL(6,2),
      lean_label      TEXT,
      trend           TEXT,
      competitive     BOOLEAN,
      potentially_flippable BOOLEAN,
      elections_counted INTEGER,
      latest_year     INTEGER,
      latest_dem_pct  DECIMAL(6,2),
      latest_margin   DECIMAL(6,2),
      election_history TEXT,
      updated_at      TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(state, office, district)
    );
  `).catch(() => {}); // Ignore if already exists

  if (filename.includes('lean') || filename.includes('intelligence') || filename.includes('competitive')) {
    for (const row of rows) {
      try {
        await db.query(`
          INSERT INTO district_partisan_lean
            (state, office, district, lean_index, lean_label, trend,
             competitive, potentially_flippable, elections_counted,
             latest_year, latest_dem_pct, latest_margin, election_history, updated_at)
          VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW())
          ON CONFLICT (state, office, district)
          DO UPDATE SET
            lean_index = EXCLUDED.lean_index,
            lean_label = EXCLUDED.lean_label,
            trend = EXCLUDED.trend,
            competitive = EXCLUDED.competitive,
            potentially_flippable = EXCLUDED.potentially_flippable,
            elections_counted = EXCLUDED.elections_counted,
            latest_year = EXCLUDED.latest_year,
            latest_dem_pct = EXCLUDED.latest_dem_pct,
            latest_margin = EXCLUDED.latest_margin,
            election_history = EXCLUDED.election_history,
            updated_at = NOW()
        `, [
          row.state || row.STATE,
          row.office || row.OFFICE,
          row.district || row.DISTRICT,
          parseFloat(row.lean_index || 0),
          row.lean_label || row.LEAN_LABEL,
          row.trend || null,
          row.competitive === 'True' || row.competitive === 'true' || row.competitive === '1',
          row.potentially_flippable === 'True' || row.potentially_flippable === 'true' || row.potentially_flippable === '1',
          parseInt(row.elections_counted || 0),
          parseInt(row.latest_year || 0) || null,
          parseFloat(row.latest_dem_pct || 0) || null,
          parseFloat(row.latest_margin || 0) || null,
          row.election_history || row.election_history_json || null,
        ]);
        inserted++;
      } catch (e) {
        errors++;
        if (errors <= 3) console.warn(`  Election intelligence row error: ${e.message}`);
      }
    }
  }

  return { rows: rows.length, inserted, errors };
}

/**
 * Parses all MIT Election Lab CSV files into historical_election_results.
 * Handles all column name variations across file types:
 *   - 1976-2018-house.csv       (candidatevotes, totalvotes, party, stage)
 *   - 1976-2018-senate.csv      (same)
 *   - 1976-2016-president.csv   (candidatevotes, totalvotes, party, no stage)
 *   - 2024-senate-state.csv     (votes, party_simplified)
 *   - 2024-president-state.csv  (votes, party_simplified)
 *   - 2024-*-county.csv         (votes, party_simplified, county columns)
 * Upload all files to the same source folder — parser handles each.
 */
async function parseElectionHistory(filePath, db) {
  const filename = path.basename(filePath).toLowerCase();
  const content = fs.readFileSync(filePath, 'utf-8');
  const rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });

  let inserted = 0;
  let errors = 0;
  let skipped = 0;

  // Detect file type from filename
  const is2024 = filename.includes('2024');
  const isCounty = filename.includes('county');
  const isPresident = filename.includes('president');
  const isSenate = filename.includes('senate');
  const isHouse = filename.includes('house');

  // Only process general election stage for 1976-2018 files
  // 2024 files don't have a stage column

  const BATCH = 500;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);

    for (const row of batch) {
      try {
        // ── Normalize stage ──
        // Skip primaries in historical files
        const stage = row.stage || row.STAGE || 'GEN';
        if (!is2024 && !stage.toUpperCase().includes('GEN')) {
          skipped++;
          continue;
        }

        // ── Normalize state ──
        const state = (row.state_po || row.STATE_PO || row.state || row.STATE || '').toUpperCase().trim().slice(0, 2);
        if (!state) continue;

        // ── Normalize year ──
        const year = parseInt(row.year || row.YEAR);
        if (!year || isNaN(year)) continue;

        // ── Normalize office ──
        let office = row.office || row.OFFICE || '';
        if (!office) {
          if (isHouse) office = 'US House';
          else if (isSenate) office = 'US Senate';
          else if (isPresident) office = 'President';
          else office = 'Unknown';
        }

        // ── Normalize district ──
        let district = row.district || row.DISTRICT || '';
        if (!district || district === 'NA') {
          district = (isSenate || isPresident) ? 'statewide' : '00';
        }
        district = String(district);

        // ── Normalize candidate ──
        const candidate = (row.candidate || row.CANDIDATE || 'Unknown').trim();

        // ── Normalize party ──
        // 2024 files use party_simplified, older files use party
        const rawParty = row.party_simplified || row.party_detailed || row.party || row.PARTY || '';
        const party = normalizeParty(rawParty);

        // ── Normalize votes ──
        // 2024 files use 'votes', older files use 'candidatevotes'
        const candidatevotes = parseInt(row.votes || row.candidatevotes || row.CANDIDATEVOTES || 0) || 0;
        const totalvotes = parseInt(row.totalvotes || row.total_votes || row.TOTALVOTES || 0) || 0;

        // ── County handling ──
        // For county files, append county to district to keep granularity
        let districtKey = district;
        if (isCounty) {
          const county = row.county_name || row.county || row.COUNTY || '';
          if (county) districtKey = `${district}-${county.toLowerCase().replace(/\s+/g, '_')}`;
        }

        await db.query(`
          INSERT INTO historical_election_results
            (state, district, year, office, candidate_name, party, votes, total_votes, source)
          VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
          ON CONFLICT (state, district, year, office, candidate_name)
          DO UPDATE SET
            votes = EXCLUDED.votes,
            total_votes = EXCLUDED.total_votes,
            party = EXCLUDED.party
        `, [
          state,
          districtKey,
          year,
          office,
          candidate,
          party,
          candidatevotes,
          totalvotes,
          `MIT Election Lab — ${path.basename(filePath)}`,
        ]);
        inserted++;
      } catch (e) {
        errors++;
        if (errors <= 5) console.warn(`  [${filename}] Row error: ${e.message}`);
      }
    }

    if (i > 0 && i % 10000 === 0) {
      console.log(`  Progress: ${i.toLocaleString()}/${rows.length.toLocaleString()} rows...`);
    }
  }

  console.log(`  [${filename}] ${rows.length.toLocaleString()} rows → ${inserted.toLocaleString()} inserted, ${skipped.toLocaleString()} skipped (primaries), ${errors} errors`);
  return { rows: rows.length, inserted, errors };
}

/**
 * Parses precinct_district_2024.csv into precinct_results_2024 table.
 */
async function parsePrecinct2024(filePath, db) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const rows = parse(content, { columns: true, skip_empty_lines: true, trim: true });

  let inserted = 0;
  let errors = 0;

  // Create table if it doesn't exist
  await db.query(`
    CREATE TABLE IF NOT EXISTS precinct_results_2024 (
      id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      state           CHAR(2) NOT NULL,
      district        TEXT NOT NULL,
      dem_votes       INTEGER,
      rep_votes       INTEGER,
      total_votes     INTEGER,
      dem_pct         DECIMAL(6,2),
      margin          DECIMAL(6,2),
      lean_label      TEXT,
      updated_at      TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(state, district)
    );
  `).catch(() => {});

  for (const row of rows) {
    try {
      const state = (row.state_po || row.STATE_PO || '').toUpperCase().slice(0, 2);
      const district = String(row.district || row.DISTRICT || '');
      if (!state || !district) continue;

      await db.query(`
        INSERT INTO precinct_results_2024
          (state, district, dem_votes, rep_votes, total_votes,
           dem_pct, margin, lean_label, updated_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW())
        ON CONFLICT (state, district)
        DO UPDATE SET
          dem_votes = EXCLUDED.dem_votes,
          rep_votes = EXCLUDED.rep_votes,
          total_votes = EXCLUDED.total_votes,
          dem_pct = EXCLUDED.dem_pct,
          margin = EXCLUDED.margin,
          lean_label = EXCLUDED.lean_label,
          updated_at = NOW()
      `, [
        state,
        district,
        parseInt(row.dem_votes_2024 || 0),
        parseInt(row.rep_votes_2024 || 0),
        parseInt(row.total_2024 || 0),
        parseFloat(row.dem_pct_2024 || 0),
        parseFloat(row.margin_2024 || 0),
        row.lean_label_2024 || null,
      ]);
      inserted++;
    } catch (e) {
      errors++;
      if (errors <= 3) console.warn(`  Precinct 2024 row error: ${e.message}`);
    }
  }

  return { rows: rows.length, inserted, errors };
}

// ─────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────

function normalizeParty(party) {
  if (!party) return 'unknown';
  const p = party.toUpperCase();
  if (p === 'DEMOCRAT' || p === 'DEM' || p === 'D') return 'democrat';
  if (p === 'REPUBLICAN' || p === 'REP' || p === 'R') return 'republican';
  if (p === 'INDEPENDENT' || p === 'IND' || p === 'I') return 'independent';
  if (p === 'GREEN' || p === 'GRE') return 'green';
  if (p === 'LIBERTARIAN' || p === 'LIB') return 'libertarian';
  return party.toLowerCase();
}

function detectOfficeFromFilename(filePath) {
  const name = path.basename(filePath).toLowerCase();
  if (name.includes('house')) return 'US House';
  if (name.includes('senate')) return 'US Senate';
  if (name.includes('president')) return 'President';
  return 'unknown';
}

// ─────────────────────────────────────────────────
// CLI RUNNER
// ─────────────────────────────────────────────────

if (require.main === module) {
  const args = process.argv.slice(2);
  const sourceArg = args.find(a => a.startsWith('--source='));
  const source = sourceArg?.split('=')[1];

  if (!source) {
    console.log('Usage: node ingest.js --source=<source-name>');
    console.log('Available sources:');
    Object.entries(BULK_SOURCES).forEach(([key, s]) => {
      console.log(`  ${key.padEnd(30)} ${s.status === 'loaded' ? '✓ loaded' : '○ pending'} — ${s.name}`);
    });
    console.log('\nTo see download instructions for a source:');
    console.log('  node ingest.js --source=<name> --instructions');
    process.exit(0);
  }

  if (args.includes('--instructions')) {
    const s = BULK_SOURCES[source];
    if (s) {
      console.log(`\n${s.name}`);
      console.log(s.downloadInstructions);
    }
    process.exit(0);
  }

  // Would connect to DB here in full implementation
  console.log(`Would ingest: ${source}`);
  console.log('(Connect DB to run full ingestion)');
}

module.exports = {
  BULK_SOURCES,
  ingestSource,
};
